### ISSUE TITLE
Error on grunt cep:debug with no modifications

### ISSUE THREAD

**Issue by DominikGuzei** [fcamarlinghi/grunt-init-cep#1] opened 2015-02-05 14:49 UTC
Hey there!

I installed the latest versions of `grunt-cep` and `grunt-init-cep` but get this error after setting up the template and trying to run `grunt cep:debug`. Any ideas what the problem could be?

```
localhost:prisma-universal-extension dominik$ grunt cep:debug
Running "cep:debug" (cep) task
launch profile is enabled.
Validating options...OK

Compiling bundle for Adobe photoshop - CC2014, CC...
Copying src folder...OK
Generating .debug file...OK
Generating bundle manifest...OK

Launching application...
Warning: Arguments to path.join must be strings Use --force to continue.

Aborted due to warnings.
```

**Comment by fcamarlinghi** [comment] 2015-02-05 20:52
Sorry to hear you're having trouble running the task! However, I'll need some more information to help you out as I just tried reproducing the issue locally, but without any luck.

Are you on Windows or Mac? Can you please try running the task with the `--debug` and `--verbose` flags and post the output here?

**Comment by DominikGuzei** [comment] 2015-02-06 13:17
Hey @fcamarlinghi, thanks for helping me out!
here is the verbose output:

```
grunt cep:debug --debug --verbose
Initializing
Command-line options: --debug=1, --verbose

Reading "Gruntfile.js" Gruntfile...OK

Registering Gruntfile tasks.
Initializing config...OK

Registering "grunt-cep" local Npm module tasks.
Reading /Users/dominik/Dropbox/work/projects/apps/prisma/code/prisma-universal-extension/node_modules/grunt-cep/package.json...OK
Parsing /Users/dominik/Dropbox/work/projects/apps/prisma/code/prisma-universal-extension/node_modules/grunt-cep/package.json...OK
Loading "cep.js" tasks...OK
+ cep
Loading "Gruntfile.js" tasks...OK
>> No tasks were registered or unregistered.

Running tasks: cep:debug

Running "cep:debug" (cep) task
[D] Task source: /Users/dominik/Dropbox/work/projects/apps/prisma/code/prisma-universal-extension/node_modules/grunt-cep/tasks/cep.js
Verifying property cep.debug exists in config...OK
File: [no files]
Options: bundle={"version":"0.2.3","id":"Prisma","name":"Prisma","author_name":"Dominik Guzei e.U.","description":"Global color swatches that are synchronized between multiple Photoshop documents.","ui_access":"You can run this extension by choosing<br><b>Window &gt; Extensions &gt; Prisma.</b>"}, extensions=[{"version":"0.2.3","id":"Prisma.panel","name":"Prisma","main_path":"prisma.html","script_path":"extendscript/prisma.js","icons":{"light":{"normal":"icons/icon-light.png","hover":"icons/icon-light-hover.png","disabled":"icons/icon-light-disabled.png"},"dark":{"normal":"icons/icon-dark.png","hover":"icons/icon-dark-hover.png","disabled":"icons/icon-dark-disabled.png"}},"manifest":"bundle/manifest.extension.xml"}], builds=[{"bundle":{"manifest":"bundle/manifest.bundle.cc.xml"},"products":["photoshop"],"source":"src","families":["CC2014","CC"]}], profile="launch"
launch profile is enabled.
Validating options...OK

Compiling bundle for Adobe photoshop - CC2014, CC...
Deleting staging/debug...OK
Copying src folder...
Copying src/css/prisma.css -> staging/debug/css/prisma.css
Reading src/css/prisma.css...OK
Writing staging/debug/css/prisma.css...OK
Copying src/extendscript/prisma.jsx -> staging/debug/extendscript/prisma.jsx
Reading src/extendscript/prisma.jsx...OK
Writing staging/debug/extendscript/prisma.jsx...OK
Copying src/icons/icon-dark-disabled.png -> staging/debug/icons/icon-dark-disabled.png
Reading src/icons/icon-dark-disabled.png...OK
Writing staging/debug/icons/icon-dark-disabled.png...OK
Copying src/icons/icon-dark-hover.png -> staging/debug/icons/icon-dark-hover.png
Reading src/icons/icon-dark-hover.png...OK
Writing staging/debug/icons/icon-dark-hover.png...OK
Copying src/icons/icon-dark.png -> staging/debug/icons/icon-dark.png
Reading src/icons/icon-dark.png...OK
Writing staging/debug/icons/icon-dark.png...OK
Copying src/icons/icon-light-disabled.png -> staging/debug/icons/icon-light-disabled.png
Reading src/icons/icon-light-disabled.png...OK
Writing staging/debug/icons/icon-light-disabled.png...OK
Copying src/icons/icon-light-hover.png -> staging/debug/icons/icon-light-hover.png
Reading src/icons/icon-light-hover.png...OK
Writing staging/debug/icons/icon-light-hover.png...OK
Copying src/icons/icon-light.png -> staging/debug/icons/icon-light.png
Reading src/icons/icon-light.png...OK
Writing staging/debug/icons/icon-light.png...OK
Copying src/js/lib/CSInterface-4.0.0.js -> staging/debug/js/lib/CSInterface-4.0.0.js
Reading src/js/lib/CSInterface-4.0.0.js...OK
Writing staging/debug/js/lib/CSInterface-4.0.0.js...OK
Copying src/js/lib/CSInterface-5.0.0.js -> staging/debug/js/lib/CSInterface-5.0.0.js
Reading src/js/lib/CSInterface-5.0.0.js...OK
Writing staging/debug/js/lib/CSInterface-5.0.0.js...OK
Copying src/js/prisma.js -> staging/debug/js/prisma.js
Reading src/js/prisma.js...OK
Writing staging/debug/js/prisma.js...OK
Copying src/prisma.html -> staging/debug/prisma.html
Reading src/prisma.html...OK
Writing staging/debug/prisma.html...OK
Generating .debug file...
Reading /Users/dominik/Dropbox/work/projects/apps/prisma/code/prisma-universal-extension/node_modules/grunt-cep/res/.debug...OK
Writing staging/debug/.debug...OK
Reading bundle/manifest.extension.xml...OK
Reading bundle/manifest.bundle.cc.xml...OK
Writing staging/debug/CSXS/manifest.xml...OK

Launching application...
Warning: Arguments to path.join must be strings Use --force to continue.

Aborted due to warnings.
```

I am running on MacOsX 10.8.5

**Comment by fcamarlinghi** [comment] 2015-10-13 10:45
Hello @DominikGuzei, please let me apologize about the fact that a lot of time has passed since I last got back to you. I don't know if you're still interested in using _grunt-cep_, but the last release of _grunt-cep_ and _grunt-init-cep_ should hopefully fix the issues you were experiencing on Mac. I'm closing this issue due to its age, but please feel free to file another one should you encounter other problems.

**Closed as completed by fcamarlinghi** 2015-10-13 10:45 UTC
